server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    url: jdbc:mysql://123.207.252.249:3306/mysoftware?useSSL=false&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: mch1021
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      validation-query: SELECT 'x'
      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true
#      scheam:
#       -classpath: sql/user.sql
      #validation-query: SELECT
  redis:
    host: 123.207.252.249
    port: 6379
  messages:
    basename: i81n.login
  #禁用缓存，一修改就生效，ctrl+F9
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
    date-format: yyyy-MM-dd
    favicon:
      enabled: false

  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: 1778396143@qq.com
    password: sccifzrhjvjhfieb
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    port: 465
  servlet:
    multipart:
      max-file-size: 100MB
      enabled: true
      max-request-size: 100MB


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.bill.system.entity
logging:
  path: /springboot/log